### PR TITLE
feat: replace the 'fast-url-parser' module with the 'node:url' module

### LINKED ISSUE #204: Module `punycode` is deprecated since Node.js 21
This library depends on the [`fast-url-parser` package](https://github.com/petkaantonov/urlparser) which depends on the [`punycode` builtin module](https://nodejs.org/docs/latest/api/punycode.html)... but since Node.js 21, this module is deprecated:

```
(node:4284) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```

Issue also raised on the `fast-url-parser` repository: cf. petkaantonov/urlparser#20

### PR DESCRIPTION
**Pull request by gweesin**
closed #204

### CODE REVIEW

**Comment by jimthedev** [comment]
@gweesin You probably already know this but I think @leo was previously merging on this repo but has left Vercel (if his twitter is any indication). Not so sure this is getting merged unless someone else from over there has the ability to approve. Maybe @rauchg knows who hits the buttons on this repo now?

**Comment by leo** [comment]
I indeed don't have access to this repo anymore, but I just pressed "View git blame" on the line that imports `fast-url-parser`, which took me to [this commit](https://github.com/vercel/serve-handler/commit/3554af3823ae1c50ab97b9346009316397cf46c4). That commit replaces the native `url` module with `fast-url-parser`.

I was wondering why (I don't remember the reason), but looking at the readme of the [fast-url-parser](https://www.npmjs.com/package/fast-url-parser) package and considering it has 4 million weekly downloads, it seems that the only reason why the package exists is to make the native `url` module 25x faster (e.g. for `parse()`). That's why it has the same API too.

So unless the native `url` module got a lot faster over the years (which is probably the case, but we'd have to test to what extend that is the case), using it might make `serve-handler` a lot slower in production.

But agreed that, if the owner of `fast-url-parser` is not responsive, replacing it in `server-handler` might be the only option. I think it is very likely that the native `url` module has gotten faster over the years.

**Comment by regseb** [comment]
I've run `fast-url-parser` benchmarks (higher is better) with Node v22: `fast-url-parser` is 2.5 times faster than `node:url`.

| October 15, 2024 / Node 22.9.0 | `fast-url-parser` | `node:url` | Diff |
| --- | --- | --- | --- |
| `parse()` | 509333.95 | 216544.43 | 2.35 |
| `format()` | 567429.07 | 187700.54 | 3.02 |
| `resolve("../foo/bar?baz=boom")` | 579789.47 | 193241.46 | 3.00 |
| `resolve("foo/bar")` | 579329.57 | 194313.53 | 2.98 |
| `resolve("http://nodejs.org")` | 605089.97 | 190518.45 | 3.18 |
| `resolve("./foo/bar?baz")` | 607911.60 | 187227.32 | 3.25 |

---

For your information, here is the benchmark displayed in [`fast-url-parser`'s README](https://www.npmjs.com/package/fast-url-parser#performance) dating back 11 years. `fast-url-parser` was 10 times faster.

| [December 29, 2013](https://github.com/petkaantonov/urlparser/commit/4fa8e580ad32f9c2e8f6a9001e7b9adae527402b) / Maybe Node 0.10.x | `fast-url-parser` | `node:url` | Diff |
| --- | --- | --- | --- |
| `parse()` | 509333.95 | 16459 | 24.4 |
| `format()` | 567429.07 | 15978 | 15.9 |
| `resolve("../foo/bar?baz=boom")` | 56701.419 | 6837.7 | 8.29 |
| `resolve("foo/bar")` | 80059.500 | 7038.6 | 11.4 |
| `resolve("http://nodejs.org")` | 118566.13 | 6491.1 | 18.3 |
| `resolve("./foo/bar?baz")` | 62778.648 | 6968.4 | 9.01 |

**Comment by leo** [comment]
That seems like a reasonable tradeoff to me, considering that using the native module would also make the package lighter.

Great to see that Node has gotten a lot faster. I'll try to ping someone at Vercel to merge this PR.

**Comment by AndyBitz** [comment]
Thanks for the PR @gweesin and thanks for the benchmarks @regseb!

I'll try to cut a release later today with those changes

**Review by AndyBitz — APPROVED** [review]

**Comment by jimthedev** [comment]
Thank you all for hopping on this. Really appreciate it.

**Pull request merged**
